/*
	6T Grand Eras Timeline
	This timeline will overwrite the Era Start timeline when 6T Eras is enabled

*/

-------------------------------------------------------------------------------
-- Historical Spawn Eras
-- 0 - Ancient Era
-- 1 - Classical Era
-- 2 - Post-Classical
-- 3 - Medieval Era
-- 4 - Renaissance Era
-- 5 - Industrial Era
-- 6 - Modern Era
-- 7 - Atomic Era
-- 8 - Digital Era
-- 9 - Future Era
-------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS HSD_Eras_Temp
	 (	Civilization TEXT NOT NULL UNIQUE,
		Era INTEGER DEFAULT 0);

INSERT OR REPLACE INTO HSD_Eras_Temp
(	Civilization,				Era) 
VALUES
-- Leaders
(	'LEADER_ELEANOR_FRANCE',			3 ),
(	'LEADER_ELEANOR_ENGLAND',			3 ),
(	'LEADER_GANDHI',					1 ),
(	'LEADER_LUDWIG',					5 ),
(	'LEADER_NADER_SHAH',				4 ),
(	'LEADER_KUBLAI_KHAN_MONGOLIA',		4 ),
(	'LEADER_KUBLAI_KHAN_CHINA',			4 ),
(	'LEADER_WU_ZETIAN',					3 ),
(	'LEADER_YONGLE',					4 ),
-- Major Civilizations
(	'CIVILIZATION_AMERICA',				5 ),
(	'CIVILIZATION_ARABIA',				3 ),
(	'CIVILIZATION_AUSTRALIA',			6 ),
(	'CIVILIZATION_AZTEC',				2 ),
(	'CIVILIZATION_BABYLON_STK',			0 ),
(	'CIVILIZATION_BRAZIL',				6 ),
(	'CIVILIZATION_BYZANTIUM',			3 ),
(	'CIVILIZATION_CANADA',		 	 	6 ),
(	'CIVILIZATION_CHINA',				0 ),
(	'CIVILIZATION_CREE',				2 ),
(	'CIVILIZATION_ENGLAND',				3 ),
(	'CIVILIZATION_EGYPT',				0 ),
(	'CIVILIZATION_ETHIOPIA',			2 ),
(	'CIVILIZATION_FRANCE',				5 ),
(	'CIVILIZATION_GAUL',				0 ),
(	'CIVILIZATION_GEORGIA',				2 ),
(	'CIVILIZATION_GERMANY',				3 ),
(	'CIVILIZATION_GRAN_COLOMBIA',		6 ),
(	'CIVILIZATION_GREECE',				0 ),
(	'CIVILIZATION_HUNGARY',				2 ),
(	'CIVILIZATION_INCA',				2 ),
(	'CIVILIZATION_INDIA',				1 ),
(	'CIVILIZATION_INDONESIA',			3 ),
(	'CIVILIZATION_JAPAN',				2 ),
(	'CIVILIZATION_KHMER',				3 ),
(	'CIVILIZATION_KONGO',				3 ),
(	'CIVILIZATION_KOREA',				2 ),
(	'CIVILIZATION_MAPUCHE',				2 ),
(	'CIVILIZATION_MACEDON',				1 ),
(	'CIVILIZATION_MALI',				3 ),
(	'CIVILIZATION_MAORI',		 		3 ),
(	'CIVILIZATION_MAYA',		 		2 ),
(	'CIVILIZATION_MONGOLIA',			3 ),
(	'CIVILIZATION_NETHERLANDS',			4 ),
(	'CIVILIZATION_NORWAY',				2 ),
(	'CIVILIZATION_NUBIA',				1 ),
(	'CIVILIZATION_OTTOMAN',				4 ),
(	'CIVILIZATION_PERSIA',				1 ),
-- (	'CIVILIZATION_PHOENICIA',			0 ), --Asia TSL
(	'CIVILIZATION_PHOENICIA',			1 ), --Africa TSL
(	'CIVILIZATION_POLAND',				3 ),
(	'CIVILIZATION_PORTUGAL',			3 ),
(	'CIVILIZATION_ROME',				1 ),
(	'CIVILIZATION_RUSSIA',				3 ),
(	'CIVILIZATION_SCOTLAND',			3 ),
(	'CIVILIZATION_SCYTHIA',				1 ),
(	'CIVILIZATION_SPAIN',				3 ),
(	'CIVILIZATION_SUMERIA',				0 ),
(	'CIVILIZATION_SWEDEN',				4 ),
(	'CIVILIZATION_VIETNAM',				3 ),
(	'CIVILIZATION_ZULU',				3 ),

-- Minor Civilizations
(	'CIVILIZATION_AKKAD',				0 ),
(	'CIVILIZATION_AMSTERDAM',			2 ),
(	'CIVILIZATION_ANTANANARIVO',		4 ),
(	'CIVILIZATION_ANTIOCH',				3 ),
(	'CIVILIZATION_ARMAGH',				2 ),
(	'CIVILIZATION_AUCKLAND',			5 ),
(	'CIVILIZATION_AYUTTHAYA',		 	3 ),	
(	'CIVILIZATION_BABYLON',				0 ),
(	'CIVILIZATION_BOLOGNA',		 		1 ),
(	'CIVILIZATION_BRUSSELS',			2 ),
(	'CIVILIZATION_BUENOS_AIRES',		5 ),
(	'CIVILIZATION_CAGUANA',				3 ),
(	'CIVILIZATION_CAHOKIA',				3 ),
(	'CIVILIZATION_CARDIFF',		 		2 ),
(	'CIVILIZATION_CHINGUETTI',		 	3 ),	
(	'CIVILIZATION_FEZ',		  			3 ),
(	'CIVILIZATION_GENEVA',				1 ),
(	'CIVILIZATION_GRANADA',				3 ),
(	'CIVILIZATION_HATTUSA',				0 ),
(	'CIVILIZATION_HONG_KONG',			2 ),
(	'CIVILIZATION_HUNZA',				3 ),
(	'CIVILIZATION_JAKARTA',				3 ),
(	'CIVILIZATION_JERUSALEM',			0 ),
(	'CIVILIZATION_JOHANNESBURG',		5 ),
(	'CIVILIZATION_KABUL',				0 ),
(	'CIVILIZATION_KANDY',				1 ),
-- (	'CIVILIZATION_KUMASI',				3 ),
(	'CIVILIZATION_KUMASI',				1 ), --temp
(	'CIVILIZATION_LAHORE',				0 ),
(	'CIVILIZATION_LA_VENTA',			1 ),
(	'CIVILIZATION_LHASA',				1 ),
(	'CIVILIZATION_LISBON',				1 ),
(	'CIVILIZATION_MEXICO_CITY',			3 ),
(	'CIVILIZATION_MOHENJO_DARO',		0 ),
(	'CIVILIZATION_MUSCAT',				0 ),
(	'CIVILIZATION_NALANDA',		 		2 ),
(	'CIVILIZATION_NAN_MADOL',			3 ),
(	'CIVILIZATION_NAZCA',		 		0 ),
(	'CIVILIZATION_NGAZARGAMU',			1 ),
(	'CIVILIZATION_PALENQUE',			2 ),
(	'CIVILIZATION_PRESLAV',				0 ),
(	'CIVILIZATION_RAPA_NUI',			2 ),
(	'CIVILIZATION_SAMARKAND',		 	0 ),
(	'CIVILIZATION_SEOUL',				1 ),
(	'CIVILIZATION_SINGAPORE',			2 ),
(	'CIVILIZATION_STOCKHOLM',			1 ),
(	'CIVILIZATION_TARUGA',				1 ),
(	'CIVILIZATION_TORONTO',				4 ),
(	'CIVILIZATION_VALLETTA',			1 ),
(	'CIVILIZATION_VATICAN_CITY',		1 ),
(	'CIVILIZATION_VILNIUS',				1 ),
(	'CIVILIZATION_WOLIN',		 		2 ),
(	'CIVILIZATION_YEREVAN',				0 ),
(	'CIVILIZATION_ZANZIBAR',			2 ),

-- DO NOT DELETE OR EDIT THE LINES BELOW
(	'END_OF_INSERT',				NULL	);	
-- Remove "END_OF_INSERT" entry 
DELETE FROM HSD_Eras_Temp WHERE Civilization ='END_OF_INSERT';

INSERT OR REPLACE INTO HistoricalSpawnEras	(Civilization, Era)
	SELECT Civilization, Era
	FROM HSD_Eras_Temp WHERE EXISTS (SELECT * FROM Eras WHERE EraType = 'ERA_6T_POST_CLASSICAL');

DROP TABLE HSD_Eras_Temp;